-- LEKKER RUGBY APP: shared voting database
create table if not exists public.votes (
 id bigint generated by default as identity primary key,
 submitted_at timestamptz not null default now(),
 pos_1 text not null, pos_2 text not null, pos_3 text not null,
 pos_4 text not null, pos_5 text not null, pos_6 text not null,
 pos_7 text not null, pos_8 text not null, pos_9 text not null,
 pos_10 text not null, pos_11 text not null, pos_12 text not null,
 pos_13 text not null, pos_14 text not null, pos_15 text not null
);
alter table public.votes enable row level security;
create policy "public vote insert" on public.votes for insert to anon with check (true);
create policy "public vote read" on public.votes for select to anon using (true);
